#!/usr/bin/env python3
"""Build reproducible patient-level train/val/test splits."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create patient-level train/val/test splits for MU-Glioma-Post."
    )
    parser.add_argument(
        "--summary-csv",
        type=Path,
        default=Path("metadata/timepoint_summary.csv"),
        help="Timepoint summary generated by build_phase1_audit.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("metadata"),
        help="Directory where split files will be written.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=20260310,
        help="Random seed for reproducible assignment.",
    )
    return parser.parse_args(argv)


def write_split_list(path: Path, patient_ids: list[str]) -> None:
    path.write_text("\n".join(patient_ids) + "\n", encoding="ascii")


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    summary = pd.read_csv(args.summary_csv)
    patient_ids = sorted(summary["patient_id"].drop_duplicates().tolist())
    if not patient_ids:
        raise SystemExit("No patient IDs found in the timepoint summary.")

    rng = np.random.default_rng(args.seed)
    shuffled = patient_ids.copy()
    rng.shuffle(shuffled)

    total = len(shuffled)
    train_end = int(np.floor(total * 0.70))
    val_end = int(np.floor(total * 0.85))

    split_map = {
        "train": sorted(shuffled[:train_end]),
        "val": sorted(shuffled[train_end:val_end]),
        "test": sorted(shuffled[val_end:]),
    }

    output_dir = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    write_split_list(output_dir / "train_patients.txt", split_map["train"])
    write_split_list(output_dir / "val_patients.txt", split_map["val"])
    write_split_list(output_dir / "test_patients.txt", split_map["test"])

    rows = []
    for split_name, ids in split_map.items():
        for patient_id in ids:
            rows.append({"patient_id": patient_id, "split": split_name, "seed": args.seed})
    pd.DataFrame(rows).sort_values(["split", "patient_id"], kind="stable").to_csv(
        output_dir / "splits.csv",
        index=False,
    )

    for split_name, ids in split_map.items():
        print(f"{split_name}: {len(ids)} patients", flush=True)
    print(f"Wrote {output_dir / 'splits.csv'}")


if __name__ == "__main__":
    main()
