#!/usr/bin/env python3
"""Generate Phase 2 visual QC artifacts for MU-Glioma-Post."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
from matplotlib.colors import BoundaryNorm, ListedColormap
import nibabel as nib
import numpy as np
import pandas as pd


MODALITY_ORDER = ("t1n", "t1c", "t2f", "t2w")
OVERLAY_MODALITIES = ("t1c", "t2w")
LABEL_COLORS = {
    1: "#ffdd57",
    2: "#ff6b6b",
    3: "#4ecdc4",
    4: "#5b8def",
}
OVERLAY_CMAP = ListedColormap(
    ["#000000"] + [LABEL_COLORS.get(label, "#ffffff") for label in range(1, 6)]
)
OVERLAY_NORM = BoundaryNorm(np.arange(-0.5, 5.6, 1.0), OVERLAY_CMAP.N)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate random-case visual QC artifacts for MU-Glioma-Post."
    )
    parser.add_argument(
        "--dataset-root",
        type=Path,
        default=Path("PKG-MU-Glioma-Post/MU-Glioma-Post"),
        help="Root directory containing patient folders.",
    )
    parser.add_argument(
        "--manifest-csv",
        type=Path,
        default=Path("metadata/manifest.csv"),
        help="Manifest generated by build_phase1_audit.py.",
    )
    parser.add_argument(
        "--summary-csv",
        type=Path,
        default=Path("metadata/timepoint_summary.csv"),
        help="Timepoint summary generated by build_phase1_audit.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("qc"),
        help="Directory for QC outputs.",
    )
    parser.add_argument(
        "--sample-count",
        type=int,
        default=12,
        help="Number of complete timepoints to sample.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=20260310,
        help="Random seed for reproducible case selection.",
    )
    return parser.parse_args()


def load_volume(path: Path) -> np.ndarray:
    return np.asarray(nib.load(str(path)).dataobj, dtype=np.float32)


def normalize_slice(slice_2d: np.ndarray) -> np.ndarray:
    finite = np.isfinite(slice_2d)
    if not finite.any():
        return np.zeros_like(slice_2d, dtype=np.float32)
    values = slice_2d[finite]
    low = np.percentile(values, 1)
    high = np.percentile(values, 99)
    if high <= low:
        high = values.max()
        low = values.min()
    if high <= low:
        return np.zeros_like(slice_2d, dtype=np.float32)
    clipped = np.clip(slice_2d, low, high)
    return (clipped - low) / (high - low)


def choose_tumor_slice(mask: np.ndarray) -> int:
    coords = np.argwhere(mask > 0)
    if coords.size == 0:
        return mask.shape[2] // 2
    return int(np.round(coords[:, 2].mean()))


def tumor_bbox(mask_slice: np.ndarray) -> tuple[int, int, int, int] | None:
    coords = np.argwhere(mask_slice > 0)
    if coords.size == 0:
        return None
    x_min, y_min = coords.min(axis=0)
    x_max, y_max = coords.max(axis=0)
    return int(x_min), int(y_min), int(x_max - x_min + 1), int(y_max - y_min + 1)


def save_case_panel(case_key: str, volumes: dict[str, np.ndarray], panel_dir: Path) -> None:
    center_z = volumes["t1c"].shape[2] // 2
    fig, axes = plt.subplots(2, 2, figsize=(10, 10))
    for axis, modality in zip(axes.flat, MODALITY_ORDER):
        axis.imshow(normalize_slice(volumes[modality][:, :, center_z]).T, cmap="gray", origin="lower")
        axis.set_title(f"{modality} z={center_z}")
        axis.axis("off")
    fig.suptitle(f"{case_key} center-slice panel", fontsize=14)
    fig.tight_layout()
    fig.savefig(panel_dir / f"{case_key}_panel.png", dpi=180, bbox_inches="tight")
    plt.close(fig)


def save_case_overlays(case_key: str, volumes: dict[str, np.ndarray], overlay_dir: Path) -> dict[str, object]:
    mask = volumes["tumor_mask"]
    overlay_z = choose_tumor_slice(mask)
    mask_slice = mask[:, :, overlay_z]
    bbox = tumor_bbox(mask_slice)
    labels = sorted(int(value) for value in np.unique(mask_slice) if value > 0)

    fig, axes = plt.subplots(1, len(OVERLAY_MODALITIES), figsize=(12, 6))
    if len(OVERLAY_MODALITIES) == 1:
        axes = [axes]

    legend_handles = []
    for label in labels:
        color = LABEL_COLORS.get(label, "#ffffff")
        legend_handles.append(mpatches.Patch(color=color, label=f"label {label}"))

    for axis, modality in zip(axes, OVERLAY_MODALITIES):
        image_slice = normalize_slice(volumes[modality][:, :, overlay_z]).T
        mask_display = np.ma.masked_where(mask_slice.T == 0, mask_slice.T)
        axis.imshow(image_slice, cmap="gray", origin="lower")
        axis.imshow(mask_display, cmap=OVERLAY_CMAP, norm=OVERLAY_NORM, alpha=0.35, origin="lower")
        if bbox is not None:
            rect = mpatches.Rectangle(
                (bbox[0], bbox[1]),
                bbox[2],
                bbox[3],
                linewidth=1.5,
                edgecolor="#ffd166",
                facecolor="none",
            )
            axis.add_patch(rect)
        axis.set_title(f"{modality} overlay z={overlay_z}")
        axis.axis("off")

    if legend_handles:
        fig.legend(handles=legend_handles, loc="lower center", ncol=max(1, len(legend_handles)))
    fig.suptitle(f"{case_key} tumor-mask overlays", fontsize=14)
    fig.tight_layout(rect=(0, 0.06, 1, 1))
    fig.savefig(overlay_dir / f"{case_key}_overlays.png", dpi=180, bbox_inches="tight")
    plt.close(fig)

    return {
        "overlay_slice_z": overlay_z,
        "mask_labels": "|".join(str(label) for label in labels),
        "tumor_bbox_xywh": "" if bbox is None else "|".join(str(value) for value in bbox),
        "tumor_voxel_count": int(np.count_nonzero(mask)),
    }


def save_case_histograms(case_key: str, volumes: dict[str, np.ndarray], hist_dir: Path) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(10, 8))
    for axis, modality in zip(axes.flat, MODALITY_ORDER):
        data = volumes[modality]
        values = data[data > 0]
        if values.size == 0:
            axis.set_title(f"{modality} histogram (empty)")
            axis.axis("off")
            continue
        upper = np.percentile(values, 99.5)
        clipped = values[values <= upper]
        axis.hist(clipped, bins=100, color="#284b63", alpha=0.9)
        axis.set_title(modality)
        axis.set_xlabel("intensity")
        axis.set_ylabel("voxels")
    fig.suptitle(f"{case_key} nonzero-intensity histograms", fontsize=14)
    fig.tight_layout()
    fig.savefig(hist_dir / f"{case_key}_hist.png", dpi=180, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    args = parse_args()
    manifest = pd.read_csv(args.manifest_csv)
    summary = pd.read_csv(args.summary_csv)

    complete = summary[(summary["issue_count"] == 0) & (summary["has_mask"] == True)].copy()
    if complete.empty:
        raise SystemExit("No complete timepoints available for QC sampling.")

    sample_count = min(args.sample_count, len(complete))
    sample = complete.sample(n=sample_count, random_state=args.seed).sort_values(
        ["patient_id", "timepoint"],
        kind="stable",
    )

    output_dir = args.output_dir
    panel_dir = output_dir / "random_case_panels"
    overlay_dir = output_dir / "mask_overlays"
    hist_dir = output_dir / "histograms"
    for directory in (panel_dir, overlay_dir, hist_dir):
        directory.mkdir(parents=True, exist_ok=True)

    sampled_rows: list[dict[str, object]] = []
    for row in sample.itertuples(index=False):
        case_key = f"{row.patient_id}_{row.timepoint}"
        case_rows = manifest[
            (manifest["patient_id"] == row.patient_id)
            & (manifest["timepoint"] == row.timepoint)
            & (manifest["readable"] == True)
        ]
        file_map = {
            modality: args.dataset_root / file_path
            for modality, file_path in zip(case_rows["modality"], case_rows["file_path"])
        }
        volumes = {modality: load_volume(file_map[modality]) for modality in (*MODALITY_ORDER, "tumor_mask")}

        save_case_panel(case_key, volumes, panel_dir)
        overlay_stats = save_case_overlays(case_key, volumes, overlay_dir)
        save_case_histograms(case_key, volumes, hist_dir)

        sampled_rows.append(
            {
                "patient_id": row.patient_id,
                "timepoint": row.timepoint,
                **overlay_stats,
            }
        )
        print(f"Rendered QC for {case_key}", flush=True)

    pd.DataFrame(sampled_rows).to_csv(output_dir / "sampled_timepoints.csv", index=False)
    print(f"Wrote {output_dir / 'sampled_timepoints.csv'}")


if __name__ == "__main__":
    main()
